FROM node:24-alpine

WORKDIR /workspace

COPY package*.json ./

COPY apps/frontend/package*.json ./apps/frontend/
COPY apps/backend/package*.json ./apps/backend/
COPY packages/shared/package*.json ./packages/shared/

RUN npm install

COPY . .

EXPOSE 3000
EXPOSE 4000